#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "dev" ]; then
  echo "dev branch commit is blocked"
  exit 1
fi

if [ "$branch" = "master" ]; then
  echo "master branch commit is blocked"
  exit 1
fi

if [ "$branch" = "main" ]; then
  echo "main branch commit is blocked"
  exit 1
fi

if [ "$branch" = "soft" ]; then
  echo "soft branch commit is blocked"
  exit 1
fi
